version: '3.8'

services:
  digit-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: base  
    command: npm run dev
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
