version: '3.8'

services:
  digit-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner 
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/chat.db
    ports:
      - "3000:3000"
    volumes:
      - chat_data:/app/data  
    restart: unless-stopped

volumes:
  chat_data:
    driver: local
