version: '3.8'

services:
  digit-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner 
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/chat.db
      - HOST_SERVICE_URL=http://host.docker.internal:8080
      - ENABLE_MCP=true
      - MCP_DATABASE_SERVER_URL=http://host.docker.internal:8080/mcp
    ports:
      - "3000:3000"
    volumes:
      - chat_data:/app/data  
    restart: unless-stopped
    # Enable access to host services on macOS/Windows
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  chat_data:
    driver: local
